### ISSUE TITLE
mkcloud needs to automatically log itself to a file

### ISSUE THREAD

**Issue by aspiers** [SUSE-Cloud/automation#1191]
Obviously `mkcloud` needs to retain the ability to output to the CLI, but the same output should also be preserved in a log file for future reference.  We could use [this trick](http://stackoverflow.com/questions/3173131/redirect-copy-of-stdout-to-log-file-from-within-bash-script-itself).

**Comment by aspiers** [comment]
@vuntz I got this idea from `/root/manual.vuntz/runme` on `mkcloud1`, and it seems reasonable to me to make `mkcloud` do it by default (just like `chef-client` always logs to a file). Thoughts?

/cc @jdsn @bmwiedemann

**Comment by jdsn** [comment]
Nice idea.  +1 (for the idea)

**Comment by nicolasbock** [comment]
Good idea! This would be quite useful.
