### ISSUE TITLE
setupcompute and instcompute are misnomers

### ISSUE THREAD

**Issue by aspiers** [SUSE-Cloud/automation#269]
The `setupcompute` and `instcompute` steps don't just setup and install compute nodes, they also do controller and storage nodes.  So they should be renamed to something more general.  I can't yet think of the right word though, sorry ;-)

**Comment by jdsn** [comment]
In the beginning all nodes were also compute nodes. Thats where this naming came from.
If you think that we should change it and break all usages of mkcloud that list all steps explicitly - well we could do that.

But that requires a new name - right.

Just a quick idea: setupcloudnodes and instcloudnodes (or even installcloudnodes)

We could even change the naming and keep support for the old names and if still used spit out some bothering log lines to help people to change their setup.

**Comment by aspiers** [comment]
Maybe just `setupnodes` and `instnodes`?  It's kind of obvious they're cloud-related ;-)

Yes, great idea to keep backwards compatibility too!
