### ISSUE TITLE
mkcloud has cryptic step names

### ISSUE THREAD

**Issue by aspiers** [SUSE-Cloud/automation#292]
There are a bunch of expandable steps called `alias_*` and I have no idea why.

**Comment by jdsn** [comment]
The alias_* steps are only used internally to create the expansions. The alias_* aliases are lists of steps that must always be queued in this order. They exist to reduce duplication. And to only have to change one place when a new step is added to the default workflow.

The expanding steps that should be used when calling mkcloud are [all, all_noreboot, plain, instonly].

**Comment by aspiers** [comment]
> The alias_* steps are only used internally to create the expansions.

Then why are they listed in the usage text?  You added them in bad918f.  If they are really only for internal usage, they should not be visible in the interface, and they should also the convention for prefixing private symbols with an underscore, e.g. `_alias_new_admin` or similar.

**Comment by aspiers** [comment]
@jdsn Please can you confirm they should not be in the usage text?

**Comment by jdsn** [comment]
@aspiers well yes they should not be in the usage. But I guess it makes sense to document them inline instead.
