### ISSUE TITLE
want_sles=12 + cloudsource=GM5 | GM5+up doesnt work

### ISSUE THREAD

**Issue by mimi1vx** [SUSE-Cloud/automation#308]

**Comment by aspiers** [comment]
"doesn't work" is not a helpful bug report...

**Comment by mimi1vx** [comment]
in fstab is : 

    root@crowbar:/srv/tftpboot/suse-12.0/repos # cat /etc/fstab
    clouddata.cloud.suse.de:/srv/nfs/suse-11.3/install /srv/tftpboot/suse-11.3/install nfs    ro,nosuid,rsize=8192,wsize=8192,hard,intr,nolock  0 0
    clouddata.cloud.suse.de:/srv/nfs/repos/SLES11-SP3-Pool /srv/tftpboot/suse-11.3/repos/SLES11-SP3-Pool nfs    ro,nosuid,rsize=8192,wsize=8192,hard,intr,nolock  0 0
    clouddata.cloud.suse.de:/srv/nfs/repos/SLES11-SP3-Updates /srv/tftpboot/suse-11.3/repos/SLES11-SP3-Updates nfs    ro,nosuid,rsize=8192,wsize=8192,hard,intr,nolock  0 0
    clouddata.cloud.suse.de:/srv/nfs/suse-12.0/install /srv/tftpboot/suse-12.0/install nfs    ro,nosuid,rsize=8192,wsize=8192,hard,intr,nolock  0 0
    clouddata.cloud.suse.de:/srv/nfs/repos/SLES12-Pool /srv/tftpboot/suse-12.0/repos/SLES12-Pool nfs    ro,nosuid,rsize=8192,wsize=8192,hard,intr,nolock  0 0
    clouddata.cloud.suse.de:/srv/nfs/repos/SLES12-Updates /srv/tftpboot/suse-12.0/repos/SLES12-Updates nfs    ro,nosuid,rsize=8192,wsize=8192,hard,intr,nolock  0 0
    clouddata.cloud.suse.de:/srv/nfs/repos/SUSE-Cloud-5-Updates/ /srv/tftpboot/suse-11.3/repos/SUSE-Cloud-5-Updates/ nfs    ro,nosuid,rsize=8192,wsize=8192,hard,intr,nolock  0 0
    clouddata.cloud.suse.de:/srv/nfs/repos/SUSE-Cloud-5-Pool/ /srv/tftpboot/suse-11.3/repos/SUSE-Cloud-5-Pool/ nfs    ro,nosuid,rsize=8192,wsize=8192,hard,intr,nolock  0 0


btw.. i dont see any SLE-12-Cloud-Compute repository mounted 

and in `/srv/tftpboot/suse-12.0/repos` : 

    root@crowbar:/srv/tftpboot/suse-12.0/repos # ls -al
    drwxr-xr-x 6 32004   50 4096 15. říj 13.21 SLES12-Pool
    drwxr-xr-x 8 32004   50 4096 10. dub 12.09 SLES12-Updates
    drwxr-xr-x 3 root  root 4096  9. dub 14.16 SLE12-Cloud-Compute
    drwxr-xr-x 4 root  root 4096  9. dub 14.17 SLE12-Cloud-Compute-PTF
    drwxr-xr-x 3 root  root 4096  9. dub 14.16 SLE-12-Cloud-Compute5-Pool
    drwxr-xr-x 3 root  root 4096  9. dub 14.16 SLE-12-Cloud-Compute5-Updates

but in Cloud-Compute dirs is only : 

    root@crowbar:/srv/tftpboot/suse-12.0/repos/SLE12-Cloud-Compute # ls -Rla
    drwxr-xr-x 3 root root 4096  9. dub 14.16 .
    drwxr-xr-x 8 root root 4096  9. dub 14.17 ..
     rwxr-xr-x 3 root root 4096  9. dub 14.16 download.nue.suse.com

    ./download.nue.suse.com:
    celkem 12
    drwxr-xr-x 3 root root 4096  9. dub 14.16 .
    drwxr-xr-x 3 root root 4096  9. dub 14.16 ..
    drwxr-xr-x 3 root root 4096  9. dub 14.16 install
    
    ./download.nue.suse.com/install:
    celkem 12
    drwxr-xr-x 3 root root 4096  9. dub 14.16 .
    drwxr-xr-x 3 root root 4096  9. dub 14.16 ..
    drwxr-xr-x 3 root root 4096  9. dub 14.16 SUSE-Cloud-5-GM

    ./download.nue.suse.com/install/SUSE-Cloud-5-GM: 
    celkem 12
    drwxr-xr-x 3 root root 4096  9. dub 14.16 .
    drwxr-xr-x 3 root root 4096  9. dub 14.16 ..
    drwxr-xr-x 2 root root 4096  9. dub 14.16 drpmsync

    ./download.nue.suse.com/install/SUSE-Cloud-5-GM/drpmsync:
    celkem 8
    drwxr-xr-x 2 root root 4096  9. dub 14.16 .
    drwxr-xr-x 3 root root 4096  9. dub 14.16 ..

**Comment by mimi1vx** [comment]
@aspiers @bmwiedemann  anything new ?

**Comment by aspiers** [comment]
Can you provide the full `mkcloud` config you used for this?

**Comment by mimi1vx** [comment]
export drbdnode_mac_vol= ;
        export cloud=virtual ;
        export cloudfqdn=virtual.cloud.suse.de ;
        export cloudsource=GM5+up ;
        export upgrade_cloudsource= ;
        export adminip=192.168.124.10 ;
        export hacloud= ;
        export libvirt_type= ;
        export networkingplugin= ;
        export networkingmode= ;
        export nosetestparameters= ;
        export tempestoptions='' ;
        export cephvolumenumber=1 ;
        export drbd_database_size=20 ;
        export drbd_rabbitmq_size=20 ;
        export shell= ;
        export keep_existing_hostname= ;

        export all_with_ssl= ;
        export glance_with_ssl= ;
        export keystone_with_ssl= ;
        export nova_with_ssl= ;
        export nova_shared_instance_storage= ;
        export novadashboard_with_ssl= ;

        export localreposdir_target= ;

        export cinder_backend=;
        export cinder_netapp_storage_protocol=iscsi;
        export cinder_netapp_login=openstack;
        export cinder_netapp_password=;

        export TESTHEAD= ;
        export NOINSTALLCLOUDPATTERN= ;

    clusterconfig=
    nodenumbercompute=2
    nodenumberlonelynode=0
    nodenumber=6
    want_sles12=1

**Comment by ellisab** [comment]
I have a fix for this issue:

        M?|Beta*|RC*|GMC*|GM5|GM5+up)
            cs=$cloudsource
            [[ $cs =~ GM5 ]] && cs=GM
            CLOUDDISTPATH=/install/SUSE-Cloud-5-$cs/
            CLOUDCOMPUTEPATH=$CLOUDDISTPATH
            CLOUDDISTISO="SUSE-CLOUD*1.iso"
            CLOUDCOMPUTEISO="SUSE-SLE12-CLOUD-5-COMPUTE-x86_64-GM-DVD1.iso"
            CLOUDLOCALREPOS="SUSE-Cloud-5-official"

SO CLOUDCOMPUTEISO="SUSE-SLE12-CLOUD-5-COMPUTE-x86_64-GM-DVD1.iso" instead of CLOUDCOMPUTEISO="SUSE-SLE12-CLOUD-5-COMPUTE-x86_64*Media1.iso"

Tested and it works, I can deploy sle 12 guests

**Comment by aspiers** [comment]
@mimi1vx Can you confirm that #328 fixes it for you?

**Comment by bmwiedemann** [comment]
This should fix it:
https://github.com/SUSE-Cloud/automation/commit/c8c5568adc1f50b821aafa5c3389a140229f69ee#diff-c202af9895fd7be9224b15a93a00b0ffR872
