### ISSUE TITLE
It should be possible to pick the proposals that are deployed by mkcloud

### ISSUE THREAD

**Issue by nkrinner** [SUSE-Cloud/automation#329]
When I want to create a test environment for let's say ceilometer, I currently have to deploy all barclamps up to ceilometer manually. Then I can fetch the updated ceilometer barclamp and deploy it. 

It should be possible to tell mkcloud which proposals to deploy. It could be done with a variable that contains a string that holds the requested proposals and is exported as a environment variable or using crowbar batch in a way.

**Comment by aspiers** [comment]
Won't we get this for free when [it switches to using crowbar batch](https://trello.com/c/ssI9nw9p)?  Would just need to support the `--include` option, or allow use of arbitrary YAML templates or something.

**Comment by bmwiedemann** [comment]
We got crowbar batch support now, so is there still something left to do?

**Comment by aspiers** [comment]
I don't think so.  @nkrinner ?

**Comment by aspiers** [comment]
No response -> closing. Can reopen if there is something left to do.
