### ISSUE TITLE
mkcloud proposal trying deploy manila proposal with GM5+up

### ISSUE THREAD

**Issue by mimi1vx** [SUSE-Cloud/automation#535]
With : cloudsource=GM5+up want_sles12=1 want_ceph=1 mkcloud  .. proposal

    Finished proposal heat(default) at: Fri Sep 11 07:22:43 UTC 2015
    Usage: crowbar <area> <subcommand>
      Areas: batch ceilometer ceph cinder crowbar database deployer dns glance heat ipmi keystone logging machines network neutron nfs_client node_state nova nova_dashboard ntp pacemaker provisioner rabbitmq reset reset_nodes reset_proposal suse_manager_client swift tempest trove updater
    Starting proposal manila(default) at: Fri Sep 11 07:22:53 UTC 2015
    No hooks defined for service: manila
    Usage: crowbar <area> <subcommand>
      Areas: batch ceilometer ceph cinder crowbar database deployer dns glance heat ipmi keystone logging machines network neutron nfs_client node_state nova nova_dashboard ntp pacemaker provisioner rabbitmq reset reset_nodes reset_proposal suse_manager_client swift tempest trove updater
    Error: 'crowbar manila proposal --file=/root/manila.default.proposal edit default' failed with exit code: 255
    
    $h1!!
    Error detected. Stopping mkcloud.

**Comment by toabctl** [comment]
> With : cloudsource=GM5+up want_slels12=1 want_ceph=1 mkcloud .. proposal

It's ```want_sles12``` . typo

**Comment by mimi1vx** [comment]
@toabctl  typpo only here , but log is from real run , plus i forgot add :+1: 

i use  crowbar-barclamp-crowbar-1.9.0-1.9+git.1437477743.ba6b49d
