### ISSUE TITLE
hung mkcloud does not collect supportconfigs

### ISSUE THREAD

**Issue by aspiers** [SUSE-Cloud/automation#728]
e.g. https://ci.suse.de/job/openstack-mkcloud/12920/

mkcloud should have its own timeout handler which ensures that supportconfigs are always collected if the build takes too long.

**Comment by bmwiedemann** [comment]
jenkins mkcloud does have its own timeout of 4h, but there is an additional timeout configured in jenkins that watches stalls in output... and it would be hard to replicate that.
Maybe we could setup an alarm timer for things that could timeout and use a trap ALRM to handle it.

**Comment by bmwiedemann** [comment]
is this still an issue? if so, a pointer to a more recent failure would be nice.

**Comment by aspiers** [comment]
I think I saw it a few weeks ago but I can't remember the failure.  Why would #740 help?  Isn't that only a UI change?

**Comment by bmwiedemann** [comment]
It is explained in the commit message. Jenkins kills runs when it sees no newline for 1h, which means no supportconfig is collected in that case.

**Comment by aspiers** [comment]
Oh cool! Sorry I missed that detail.  Yeah maybe that will fix it.

**Comment by aspiers** [comment]
We can reopen if we see this happen again.
