### ISSUE TITLE
motd should show origin of cloud

### ISSUE THREAD

**Issue by aspiers** [SUSE-Cloud/automation#759]
When a cloud is built via Jenkins, ideally a URL to the job should be included in `/etc/motd` on at least the Crowbar node (maybe the others too) so that when `ssh`ing to a worker cloud, it's easy to see where it came from.  This mechanism could be implemented in a way which supports arbitrary cloud descriptions, not just Jenkins URLs etc.  E.g. if I manually invoke mkcloud to test a particular feature such as compute node HA, I should be able to set a `clouddescription` variable or similar with a value like `testing compute node HA feature`.  Then anyone else who `ssh`es to my cloud can see what its purpose is.

Implementation would be in two parts:
- add `clouddescription` variable to `mkcloud`, so that the description appears in `/etc/motd`
- amend Jenkins jobs so that they set this variable appropriately (i.e. it includes a URL to the Jenkins job, and maybe other useful info too)

**Comment by aspiers** [comment]
#760 implements a lot of this, but we still need to change the triggers so that they set the new `$clouddescription`.

**Comment by jdsn** [comment]
@aspiers with https://github.com/SUSE-Cloud/automation/issues/1404 now merged, is there anything left from this issue to be implemented? If not lets close this issue.

**Comment by aspiers** [comment]
@jdsn It's looking *almost* awesome, except that:

- There is a quoting bug which I've fixed in #1410.
- For some reason `/etc/motd` is written late, in the `onadmin_add_cloud_repo` step.  This makes no sense to me.  It should be in its own `onadmin_write_motd` function, which should be called from the `setupadmin` step.  Please can you clean that up?

**Comment by jdsn** [comment]
@aspiers 
Yes, it is written late because it depends on `onadmin_add_cloud_repo` to write the file `/etc/cloudversion`. By moving it earlier, we either lose the info from that file in motd or we have to add it to motd later.

**Comment by aspiers** [comment]
> or we have to add it to motd later.

@jdsn That sounds more sensible to me.  There's no reason why we have to create `/etc/motd` in a single go, is there?
