### ISSUE TITLE
do_testsetup() has too much logic inside a string passed as argument to ssh

### ISSUE THREAD

**Issue by freyes** [SUSE-Cloud/automation#93]
The function `do_testsetup()` https://github.com/SUSE-Cloud/automation/blob/master/scripts/qa_crowbarsetup.sh#L1138 has a string of 186, which is a shell script with a lot logic passed as argument to ssh to be ran in `$novacontroller`.

This function at least should `scp` a script to novacontroller and run it in a similar way `qa_crowbarsetup.sh` is executed.

**Comment by bmwiedemann** [comment]
was solved with https://github.com/SUSE-Cloud/automation/commit/a0d1fe9bc40e82d1a54c218aaaa190159d2d2b41
